### ISSUE TITLE
"White" problems are not shown in the problem panel

### ISSUE THREAD

**Issue by bshoshany** [kenkangxgwe/vscode-lsp-wl#10]
Hello,

I love this extension, and I use it all the time to write my Mathematica package in VS Code. There is one issue that bugs me, however. While errors, warnings, and infos appear in the problems panel:

![image](https://user-images.githubusercontent.com/61846320/117554647-02ac6e00-b027-11eb-8fd7-2321ed200ffb.png)

It seems that the Wolfram engine also generates additional, sometimes useful, problems that are marked with a dotted white underline, provide information upon hovering over them with the mouse, but **do not** appear in the problems panel:

![image](https://user-images.githubusercontent.com/61846320/117554603-bd883c00-b026-11eb-876d-9d544ab74d1b.png)

Since these "white" problems cannot be found in the problems panel, there seems to be no way to find all of them, other than manually going over the entire source code and visually looking for the dotted white underline, which is obviously not feasible.

Would it be possible to add an option to display these problems in the problems panel?

Thank you!

**Comment by kenkangxgwe** [comment]
Hi @bshoshany , thanks for the feedback. If you try out the latest develop branch of https://github.com/kenkangxgwe/lsp-wl and the latest extension in VSCode, you are able to see all the diagnostics by default. If you want to filter out some of the tags, you can add them in the `settings.json`, see https://github.com/kenkangxgwe/vscode-lsp-wl#override-reporting-rules.

**Comment by bshoshany** [comment]
Great, thanks @kenkangxgwe!

**Comment by bshoshany** [comment]
When will the stable release be ready?
