### ISSUE TITLE
Do we have to start the Wolfram Language Server every time we use?

### ISSUE THREAD

**Issue by singularitti** [kenkangxgwe/vscode-lsp-wl#2]
If I do not run

```shell
wolframscript -f lsp-wl/init.wls
```

from the command line, all the features the WSL provide will be lost, i.e., autocompletion, doc, etc. Is it currently not implemented to autostart the WSL or I was merely ignorant of the correct usage?

**Comment by kenkangxgwe** [comment]
So did you find the answer through #1? You do not need to manually start the server as long as the path configuration is correct.

**Comment by singularitti** [comment]
Yep, I have thought this is caused by #1, but I think it is a separate issue for others to reference. So I made an issue. I will close it once I figure out how to use it. Thank you for your timely reply!

**Comment by singularitti** [comment]
I figure out what is the problem: it is not 
```json
"WolframLanguageServer.WolframPath": "/Applications/Mathematica.app/Contents/MacOS/wolfram",
```
is wrong, it is I had environment variables in `WLServerPath`
```json
"WolframLanguageServer.WLServerPath": "{env:HOME}/Library/Mathematica/Applications/lsp-wl",
```
Great thanks for your help and time!
