### ISSUE TITLE
Syntax highlighting is not available for Jupyter Notebook in VSCode

### ISSUE THREAD

**Issue by unlsycn** [kenkangxgwe/vscode-lsp-wl#23]
![image](https://user-images.githubusercontent.com/31343548/219587349-71399ba9-06a3-40df-bd40-61a80ac89198.png)
As preceding image the other features like hover and completion work fine.

**Comment by kenkangxgwe** [comment]
Hi, Syntax highlighting is not a feature of LSP, please find the syntax highlighting plugin of the Wolfram Language for your editor.
