### ISSUE TITLE
lsp-wl not work in vscode now...

### ISSUE THREAD

**Issue by xactor** [kenkangxgwe/vscode-lsp-wl#3]
"AST-0.11" and "Lint-0.11" are not available on the official server now, I think the 0.11 version has been deleted, the latest version 0.13 were provided. Unfortunately, they can't be used in vscode.

**Comment by physicsuniverse** [comment]
same problem. I tried so many times and so many different ways.

A better solution, is to provide the paclet file, instead of downloading it from wolfram server.

**Comment by kenkangxgwe** [comment]
Hi, please refer to https://github.com/kenkangxgwe/lsp-wl/wiki#dependency-issue to tackle with the dependency issue. Feel free to give any feedback.

**Comment by physicsuniverse** [comment]
Thank you for such a quick reply.


I indeed tried this possibility by removing the edition number couple of hours ago, well, it run for hours and I thought it is no good and shut it down.


Next time I will try run it with a VPN, hope it gets faster.


Best Regards!




------------------ Original ------------------

**Comment by kenkangxgwe** [comment]
Hi, is your problem solved?

**Comment by kenkangxgwe** [comment]
Close as obsolete.
