### ISSUE TITLE
Error: Request textDocument/documentSymbol failed

### ISSUE THREAD

**Issue by GiovanniBordiga** [kenkangxgwe/vscode-lsp-wl#4]
Hi there @kenkangxgwe ! 

First of all, thanks a lot for developing this great extension! I'm trying to transition from IntelliJ to VS Code and your extension is the most complete out there for Wolfram Language.

Now the issue is the following. While i'm writing Wolfram Language code i continuously get the output window reporting the error:

```
[Error - 6:19:32 PM] Request textDocument/documentSymbol failed.
  Message: There is a more recent duplicate request.
  Code: -32801 
```

I'm pretty sure the paths in settings are correctly configured. What could be the problem?

Thanks in advance.

**Comment by kenkangxgwe** [comment]
Yes, this error is intended behavior, you may ignore it. If you feel the output window is annoying, please shrink the tab for the time being 🤣. I will try to eliminate this error in the next release.

**Comment by GiovanniBordiga** [comment]
@kenkangxgwe I understand. Thanks!

**Comment by kenkangxgwe** [comment]
Hi Giovanni, if you check out the latest `develop` branch, the error will be suppressed. And do not let go of any other errors if you still spot any popup from the Output window. You are welcomed to send an issue.

**Comment by GiovanniBordiga** [comment]
@kenkangxgwe I'll check it out, thanks!

**Comment by GiovanniBordiga** [comment]
@kenkangxgwe yep, switched to the `develop` branch and it's working great!
