### ISSUE TITLE
Depreciation warnings

### ISSUE THREAD

**Issue by aarjaneiro** [kenkangxgwe/vscode-lsp-wl#5]
Output from WLS is giving the following as a result of loading both required paclets:
```wolfram
Lint`LintString::deprecated: 
   

   Lint paclet is deprecated.

   Lint functionality has moved to the CodeInspector paclet.

   Use the CodeInspector paclet.

   PacletInstall["CodeInspector"]


AST`ConcreteParseString::deprecated: 
   

   AST paclet is deprecated.

   AST functionality has moved to the CodeParser paclet.

   Use the CodeParser paclet.

   PacletInstall["CodeParser"]


```

**Comment by kenkangxgwe** [comment]
Hi please check out the latest develop branch in [lsp-wl](https://github.com/kenkangxgwe/lsp-wl) repo and refer to the latest README file on that branch. There are instructions of how to install CodeParser and CodeInspector paclets as well.

**Comment by kenkangxgwe** [comment]
Hi @aarjaneiro , hope you have resolved the problem by installing the latest paclets. Thanks
