### ISSUE TITLE
[Minor problem] `dap-wl` is not recognised (30 Jan 2021)

### ISSUE THREAD

**Issue by Gravifer** [kenkangxgwe/vscode-lsp-wl#6]
Trying the new `dap-wl` debugger feature, I followed the instruction in the [Readme](https://github.com/kenkangxgwe/vscode-lsp-wl#user-content-debugger-support:~:text=add%20the%20following%20configuration%20directly%20to%20the%20launch.json) to find that the run button is not working on my platform.
A more careful inspection reveals that the following exception is thrown:

<details>
<summary>dap-wl-is-down-screenshot</summary>

![dap-wl-down-screenshot](https://user-images.githubusercontent.com/44160838/106303204-d4372e00-6294-11eb-80d8-29874fb6f25e.png)

</details>

However lacking experience with VS-Code extension development I cannot pin down why the debugger is not added correctly.
I would like to see whether this may be reproduced by other users, as well as brief instructions on how to further investigate the [registering process of the "dap-wl" debugger type](https://github.com/kenkangxgwe/vscode-lsp-wl/blob/fa0f4409e9cc74df725f33f95d5e2526409ef6ec/src/extension.ts#LC61:~:text=%2F%2F%20register%20debug%20type%20%22dap%2Dwl%22). 

<details>
<summary>Platform informations</summary>

Since I do not clearly know what sort of information may be related, I offer the following:

OS: Windows 10 Professional 1909
VS Code: ![vscode-version](https://user-images.githubusercontent.com/44160838/106304578-7b689500-6296-11eb-8967-d69dbb51d43b.png)
lsp-wl.lsp-wl-client: 1.8.0

</details>

Update 2021-01-30: After an OS reboot, the debugger is now actually working, and it seems that the only problem is the exception thrown, without any other implication.

**Comment by kenkangxgwe** [comment]
This seems a `package.json` file issue. Fixed in a2dbb5730e450f2d6c2cea1614df685600070f2a. Thanks for the feedback.
