### ISSUE TITLE
Folding closed sections by default

### ISSUE THREAD

**Issue by Gravifer** [kenkangxgwe/vscode-lsp-wl#8]
I found that the MMA FE generates tokens like `(* ::Section::Closed:: *)` if you export a package file from a notebook and there are folded sections; when the package file is opened with MMA FE, these cells will be folded by default; if you open them and save them, the `Closed::` tag is removed.

I imagine we may be able to reproduce this for VS Code. I don't think we should modify the tag at all, which can leads to unnecessary trace in commits. We may only fold the section by default the first time the file is opened in the editor. 

This can reflect the author's intention if he want viewers to focus on certain passages at first and don't worry about details in the folded sections. It may be convenient for template script files, where the author may demand non-experienced users to manually paste some URL/file path in a line or two.

Actually I don't really think this is a often occurring situation 😂 so I am just putting forward this for completeness.

**Comment by kenkangxgwe** [comment]
Hi @Gravifer , since you came from #7, I think you have read from the [specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_foldingRange) that, though `foldingRange` is provided, the foldings are actually controlled by the editor itself. There's no way from the server side to control this. Will close this issue for now. if I overlooked anything in the spec, please let me know.

**Comment by Gravifer** [comment]
My thought was that this would be a job for the client rather than the server; I hoped that VS Code allowed the extension to customize the initialization of the editor interface, but didn't find relevant stuff in the spec. I now realize there even though the server may not need to initiate the folding request, It will still need to "flag" those regions for the client in some distinguishable way, which the protocol haven't specified. 
Maybe this can also be achieved with an [`.editorconfig`](https://editorconfig.org/), but I am not at all sure either.
This thread shall stay closed and serve for future reference.
